# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{samorau}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Blake Mizerany", "Pedro Belo", "Adam Wiggins"]
  s.date = %q{2010-02-11}
  s.default_executable = %q{samorau}
  s.description = %q{}
  s.email = %q{pedro@heroku.com}
  s.executables = ["samorau"]
  s.extra_rdoc_files = [
    "TODO"
  ]
  s.files = [
    ".gitignore",
     "NOTES",
     "TODO",
     "a-server.rb",
     "bin/samorau",
     "lib/heroku/samorau.rb",
     "server.rb",
     "set-env.sh",
     "test/create_check_test.rb",
     "test/create_response_check_test.rb",
     "test/delete_check.rb",
     "test/helper.rb",
     "test/manifest_check_test.rb"
  ]
  s.homepage = %q{http://heroku.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{}
  s.test_files = [
    "test/create_check_test.rb",
     "test/create_response_check_test.rb",
     "test/delete_check.rb",
     "test/helper.rb",
     "test/manifest_check_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<turn>, [">= 0"])
      s.add_development_dependency(%q<contest>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 0.9"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["~> 0.6"])
      s.add_runtime_dependency(%q<term-ansicolor>, ["~> 1.0"])
    else
      s.add_dependency(%q<turn>, [">= 0"])
      s.add_dependency(%q<contest>, [">= 0"])
      s.add_dependency(%q<sinatra>, ["~> 0.9"])
      s.add_dependency(%q<rest-client>, ["~> 1.2.0"])
      s.add_dependency(%q<yajl-ruby>, ["~> 0.6"])
      s.add_dependency(%q<term-ansicolor>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<turn>, [">= 0"])
    s.add_dependency(%q<contest>, [">= 0"])
    s.add_dependency(%q<sinatra>, ["~> 0.9"])
    s.add_dependency(%q<rest-client>, ["~> 1.2.0"])
    s.add_dependency(%q<yajl-ruby>, ["~> 0.6"])
    s.add_dependency(%q<term-ansicolor>, ["~> 1.0"])
  end
end

